[package]
name = "piet-cosmic-text"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmic-text = { version = "0.7.0", default-features = false }
ouroboros = "0.15.6"
piet = { version = "0.6.2", default-features = false }
ttf-parser = "0.18.1"
