# SPDX-License-Identifier: LGPL-3.0-or-later OR MPL-2.0
# This file is a part of `piet-cosmic-text`.
# 
# `piet-cosmic-text` is free software: you can redistribute it and/or modify it under the
# terms of either:
#
# * GNU Lesser General Public License as published by the Free Software Foundation, either
#   version 3 of the License, or (at your option) any later version.
# * Mozilla Public License as published by the Mozilla Foundation, version 2.
# 
# `piet-cosmic-text` is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU Lesser General Public License or the Mozilla Public License for more
# details.
# 
# You should have received a copy of the GNU Lesser General Public License and the Mozilla
# Public License along with `piet-cosmic-text`. If not, see <https://www.gnu.org/licenses/>.

[package]
name = "piet-cosmic-text"
version = "0.1.1"
edition = "2021"
authors = ["John Nunley <jtnunley01@gmail.com>"]
description = "A text layout engine for piet based on cosmic-text"
repository = "https://github.com/notgull/piet-cosmic-text"
license = "LGPL-3.0-or-later OR MPL-2.0"
documentation = "https://docs.rs/piet-cosmic-text"
homepage = "https://github.com/notgull/piet-cosmic-text#readme"

[dependencies]
cosmic-text = { version = "0.7.0", default-features = false, features = ["std"] }
ouroboros = { version = "0.15.6", default-features = false }
piet = { version = "0.6.2", default-features = false }
ttf-parser = { version = "0.18.1", default-features = false, features = ["glyph-names", "std"] }

[dev-dependencies]
cosmic-text = { version = "0.7.0", features = ["swash"] }
softbuffer = { version = "0.2.0", default-features = false, features = ["x11"] }
winit = { version = "0.28.1", default-features = false, features = ["x11"] }

[patch.crates-io]
cosmic-text = { git = "https://github.com/pop-os/cosmic-text.git" }
