[package]
name = "piet-cosmic-text"
version = "0.1.0"
edition = "2021"
authors = ["John Nunley <jtnunley01@gmail.com>"]
description = "A text layout engine for piet based on cosmic-text"
repository = "https://github.com/notgull/piet-cosmic-text"
license = "MIT OR Apache-2.0"

[dependencies]
cosmic-text = { version = "0.7.0", default-features = false, features = ["std"] }
ouroboros = { version = "0.15.6", default-features = false }
piet = { version = "0.6.2", default-features = false }
ttf-parser = { version = "0.18.1", default-features = false, features = ["glyph-names", "std"] }

[dev-dependencies]
cosmic-text = { version = "0.7.0", features = ["swash"] }
softbuffer = { version = "0.2.0", default-features = false, features = ["x11"] }
winit = { version = "0.28.1", default-features = false, features = ["x11"] }
